name: emobin
description: "flutter project created at 2026"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core: ^0.0.1
  feature_auth: ^0.0.1
  feature_feed: ^0.0.1
  feature_setting: ^0.0.1
  feature_security: ^0.0.1
  infra_drift: ^0.0.1
  infra_supabase: ^0.0.1
  ui_theme: ^0.0.1
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.5.2
  sqlite3_flutter_libs: ^0.5.0
  cupertino_icons: ^1.0.8
  auto_route: ^11.0.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.5
  injectable_generator: ^2.10.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
