name: feature_auth
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^11.0.0
  bloc_concurrency: ^0.2.5
  core: ^0.0.1
  fpdart: ^1.1.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  injectable: ^2.5.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.5
  flutter_lints: ^5.0.0
  injectable_generator: ^2.10.0
  freezed: ^3.2.5
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
