name: infra_drift
description: "Drift-backed infrastructure implementations."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  feature_feed: ^0.0.1
  injectable: ^2.5.2
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.9.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.5
  flutter_lints: ^5.0.0
  injectable_generator: ^2.10.0
  drift_dev: ^2.17.0

flutter:
